/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "game.h"
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_JNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_JNIWrapper_on_1surface_1created
        (JNIEnv* env, jclass jc)
{
    on_surface_created();
}

/*
 * Class:     com_example_myapplication_JNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_JNIWrapper_on_1surface_1changed
        (JNIEnv* env, jclass jc, jint width, jint height)
{
    on_surface_changed();
}

/*
 * Class:     com_example_myapplication_JNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_JNIWrapper_on_1draw_1frame
        (JNIEnv *, jclass)
{
    on_draw_frame();
}

#ifdef __cplusplus
}
#endif